### ISSUE TITLE
Come up with a request middleware system for things like session state and CSRF tokens

### ISSUE THREAD

**Issue by ianthetechie** [ianthetechie/SwiftCGI#9]

**Comment by toddbluhm** [comment]
@ianthetechie I know your not a node fan, but one thing I do really like is how expressjs does its middleware and routing. Middleware is essentially just a function with 3 params, the request, the response, and a callback to signal the middleware is done (or no callback if terminating the response within the middleware). Something like that could be achieved through protocols. Not really sure since I have been out of swift a while, but just an idea (no I am not proposing we turn swift into js, just the ease of use and simplicity of the middleware system is nice in this particular case).

**Comment by ianthetechie** [comment]
Thanks for the input @toddbluhm! I am actually considering something very similar to this right now. All approaches to middleware that I can think of function in a very similar way. The two specific problems I'm grappling with now are how to return the output of middleware 1) preserving strong types, and 2) in a way that is accessible from the request handler.

In Python frameworks, you can just create a new property on the request object (i.e. request.session). Obviously you can't do that in Swift. I have considered using extensions on the `FCGIRequest` class to add properties computed by middleware. While such an approach would meet both of my requirements above, I don't particularly like (my initial version of) it for several reasons. I want middleware to be easily configurable _outside_ the framework, but I would prefer "configurable" to be a little simpler than writing class extensions ;) Writing a couple extensions (that define the same property) to address each style of session management (none, memory, database...) doesn't seem very maintainable or configurable.

A much more configurable approach would be to register middeware handlers (functions) that return their data as a dictionary. These would then be aggregated and passed to the request handler. This is a relatively clean, maintainable approach that meets my second requirement, but it cannot be strongly (or at least richly) typed. We would have to use dictionaries of type `[String: String]` or `[String: AnyObject]`, which doesn't sit well with me.

It may be that my vision is too idealistic, but I'd like to have a good think over it before giving up.

Thanks for the input! If you have any suggestions on the clarified dilemma, I'd love to hear them!

**Comment by toddbluhm** [comment]
@ianthetechie One thing I do like about the extension approach is that you could make each middleware  be its own separate project/plugin. So instead of including (memory, database, etc...) within this project, split them out into separate github projects and use something like cocoa pods to do plugin integration. You could also keep the flexibility of the dictionary approach by having a dictionary on each request/response class for custom properties. So really only major middleware will extend, while just basic or simple can still use dictionary approach.

Maybe thats too convoluted. It is a difficult decision to make and one that will have a drastic affect on this project. Either way you chose will have its own pros and cons. I wish I could be of more help in the language specific department, but its been too long. Hopefully I will be getting into some iOS dev this year with my company and that will help get me back up to speed.

**Comment by ianthetechie** [comment]
@toddbluhm Yeah, I have also considered the modularity benefits of the extension approach. It really fits with the modular microframework paradigm, and would allow you to eliminate unnecessary components from the final binary. And would keep the code very clean (i.e. accessing `request.session` instead of `request.middlewareData["session"] as? [String: String]`). I don't particularly like the idea of mucking up the configuration process with cocoapods configuration, but I think that would still be preferable to the dictionary approach. Unfortunately, Swift support for CocoaPods is still very beta but I could give that a shot. Out of curiosity, why do you recommend multiple git repositories? I think it seems a bit odd to separate something into its own repository if it can't really build on its own.

The more I think about it, the more I feel that in a language with such a good typing system that it'd be some sort of cardinal sin to use the dictionary approach. But as you say, I'm aware either choice will have a major impact on the project...

**Comment by toddbluhm** [comment]
@ianthetechie Good point about the fact that each middleware individual can't stand on its own. I guess the separate repos comes from a few sources. It allows for community contribution back to an individual middleware component or even allowing someone else to take over that component. It allows for easier cocoapod separation (if one goes that route and assuming cocoapods would make that easy), and finally in the node world thats normal. 

All middleware for express are in their own repos so that the community can contribute back easily or take over the project if necessary. Expressjs used to be all combined into one project, but in 3.0 they split everything out because updating one piece of middleware would cause the entire project to have to be updated. In a small project combining everything is fine, but if this takes off, it might be easier to have community contribute back to individual middleware rather than the project as a whole. Its just an organizational thing. Might be more hassle than its worth right now :) Maybe build it now with that possibility for the future?

**Comment by ianthetechie** [comment]
@toddbluhm hmm, yeah, I see the idea there. It would separate things out for ease of contribution without forking a whole framework... I think that would only be viable if I can get cocoapods working, but I think that might be a good idea.

After discussing the current dilemma extensively with my buddy @lseelenbinder, I'm heavily leaning towards extensions encapsulated inside frameworks (that reference the SwiftCGI framework) to make the build process clean and simple. I think extensions will do everything I want, and will further promote the modular development of this as a "microframework" with modules that you can add as you so desire to be as feature-rich or minimal as you like. You won't have to install the kitchen sink to get a soap dispenser :P

**Comment by toddbluhm** [comment]
Exactly!

**Comment by ianthetechie** [comment]
Thanks for the input :+1: I think the dilemma has been adequately solved :)
